### PR TITLE
Support Apollo Engine client awareness

### PR DESCRIPTION
**Pull request by tw0517tw**
https://www.apollographql.com/docs/platform/client-awareness.html#Setup

Supports getting `name` and `version` from ApolloClient config.

### CODE REVIEW

**Comment by jaydenseric** [comment]
Sorry for the delay! I hope to review this in the next few days, in principle I support the change :)

**Comment by KillerCodeMonkey** [comment]
@jaydenseric is it possible to look into it again?

The failing test is only the file size limit.

Actually we can not distinguish our clients, because all clients are tracked by "Unidentified clients"

**Comment by StefanFeederle** [comment]
There is a workaround:

```javascript
const httpLink = createUploadLink({
   uri: myUrl,
   headers: {
      'apollographql-client-name': myAppName,
      'apollographql-client-version': myAppVersion,
   },
});
```

**Comment by KillerCodeMonkey** [comment]
@StefanFeederle yes i know, sure. But if the ApolloClient provides the ability to set these options during client creation a link should pass through these options and do not break default apollo behavior. Thatswhy i am asking :)

Thanks for the response.

**Comment by KillerCodeMonkey** [comment]
Nice. Maybe i can Test it this evening or tomorrow morning.

Jayden Seric <notifications@github.com> schrieb am So., 7. Juli 2019, 08:34:

**Comment by KillerCodeMonkey** [comment]
seems to work 👍

**Pull request merged**
