### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
https://twitter.com/SemanticRelease/status/1249795728253353986

### CODE REVIEW

**Comment by jaydenseric** [comment]
Thanks for the suggestion, but there are a few reasons not to do it this way.

**Comment by jaydenseric** [comment]
Sorry, pressed "Comment" early, reasons coming…

**Comment by jaydenseric** [comment]
Semver for `peerDependencies` should be quite similar conceptually for that of `dependencies` and `devDependencies`. If you did `">=0.12.3"` in `dependencies`, when a future major version with breaking changes is out, you wouldn't want to automatically pull in those breaking changes. For peer dependencies, we don't want to automatically declare support for major versions with breaking changes.

Note that some package managers (including future npm) install `peerDependencies` automatically, and there are `npx` scripts and other utilities that install peer dependencies automatically. We need to be careful to only declare support for major versions know to be compatible.

Regarding the verbose syntax of the current value. Normally I use semver range syntax (` - `), instead of the verbose ` || ` chain:

https://github.com/jaydenseric/graphql-upload/blob/a3b7b31406aa47567ced0b60eea1cd764db8932c/package.json#L45

Although, in this case we matched exactly the peer dependency Apollo Client declares. This package doesn't actually use `graphql`; here is an explanation why the peer dep was recently added to this package: https://github.com/jaydenseric/apollo-upload-client/pull/196 .

**Comment by MichaelDeBoey** [comment]
@jaydenseric `apollo-client` just merged my PR (https://github.com/apollographql/apollo-client/pull/6594) to do it in their repo too.

**Comment by jaydenseric** [comment]
Thanks for sharing, but I'm quite sure they've made a mistake.

**Comment by benjamn** [comment]
Yep, this was a mistake for Apollo Client. Thanks for the explanation @jaydenseric!

**Pull request closed without merging**
