### PR TITLE
Add isExtractableFile, appendFile, FormData options

### LINKED ISSUE #172: Schema stitching support
Hi!

I have been working on [graphql-tools-fork](https://github.com/yaacovCR/graphql-tools-fork) and although I am not sure myself that gateway forwarding of files to subschemas is the best idea, it certainly has been a requested idea (https://github.com/jaydenseric/graphql-upload/issues/56, https://github.com/apollographql/graphql-tools/issues/671), and I am hoping to support it within the fork.

One approach based on your comment (https://github.com/jaydenseric/apollo-upload-client/pull/79#issuecomment-380669915) is to expand extract-files to just handle streams in addition to files.

This is a bit tricky for my use case, as what the fork does automatically is populate the delegated variables with the value of the variable from the first schema, i.e. a promise that resolves to an object with a createReadStream method, not a stream itself.

My thought is to spend a bit longer parsing the query based on the schema and to actually look for variables of type GraphQLUpload. Then I will await know that those promises if they successfully resolve will resolve appropriately to the correct streams, and I will await Promise.all() them. I think I can handle batching there, but I am not quite sure.

What do you think about this approach? It would require passing the schema manually on link creation, I believe, but otherwise I think it would be doable?

Do you think it belongs in a PR to this repository or a separate project?

### PR DESCRIPTION
**Pull request by yaacovCR**
Closes #172. Simply adding customization options for apollo-upload-client greatly facilitates creation of a link that can support schema stitching.

See one implementation at:

https://github.com/yaacovCR/graphql-tools-fork/blob/with-apollo-upload-client/src/links/createServerHttpLink.ts

### CODE REVIEW

**Comment by yaacovCR** [comment]
Thoughts on this?

**Comment by yaacovCR** [comment]
Done.

**Comment by yaacovCR** [comment]
Except the part about making a separate PR, if you are not into merging, I will hold off for now on that. :)

**Comment by yaacovCR** [comment]
Hope you are sleeping better!

No real rush, just giving you a reminder. :)

**Comment by yaacovCR** [comment]
@jaydenseric anything I need to do to update this?

**Comment by jaydenseric** [comment]
I was working on documentation and changelog entries for it last night, and hope to finish it up sometime soon. I’ll take it from here :)

**Comment by yaacovCR** [comment]
Cool, thanks!

**Comment by jaydenseric** [comment]
A little more work needs to be done before this can be released - testing it out in with [the example project](https://github.com/jaydenseric/apollo-upload-examples) revealed that the way `FormData` defaults to the global crashes Node.js during Next.js SSR, because the global is not defined.

Screen Shot 2020-03-17 at 9 08 54 am

**Comment by yaacovCR** [comment]
I guess it used to work because the link was never used server-side. I would think that is just incorrect usage, because in theory the link could be used server-side and so FormData should be required to be defined when using SSR via polyfill or argument.

Not sure, though!

**Comment by yaacovCR** [comment]
For backwards compatible, I guess FormData should be set to default at runtime rather than link creation, but that is not parallel to fetch, seems wrong.

**Comment by yaacovCR** [comment]
Actually, i guess whatever, as long as fetch and FormData treated the same

**Comment by jaydenseric** [comment]
It's a tricky one! Either way the solution will be a little opinionated. It's probably ok for `FormData` to be treated differently to `fetch`, since *very* few people are uploading files in SSR and everyone already polyfills `fetch`.

I'm not totally against requiring `FormData` to be either polyfilled or specified in config like `fetch`, but if we choose that solution we need figure out and document the best way to do it so that useless polyfills don't make their way into people's client bundles.

**Comment by yaacovCR** [comment]
I guess cross-fetch in the example is similarly required to be included, but not being used, I guess then the defaults for both should just be substituted at runtime, doubt significant increase in execution time/memory use.

**Comment by yaacovCR** [comment]
Do you want me to modify PR?

**Comment by yaacovCR** [comment]
I think runtime defaulting is least breaking change and that's the way I would go at this point.

**Comment by jaydenseric** [comment]
`cross-fetch` is done in such a way that `node-fetch` is eliminated from client bundles by the the sorts of bundlers/minifiers Next.js uses.

> Do you want me to modify PR?

No, if you would like to work on a solution please do it as a new PR against `master` 👍

**Comment by jaydenseric** [comment]
To test it out with the examples project:

1. Download or clone the project: https://github.com/jaydenseric/apollo-upload-examples
2. Follow the setup instructions for [API](https://github.com/jaydenseric/apollo-upload-examples/tree/master/api) and [app](https://github.com/jaydenseric/apollo-upload-examples/tree/master/app). 
3. Run the API.
4. In the `app` directory, run `npx install-from ~/local/path/to/apollo-upload-client/repo/dir`. Run this anytime you test changes to the local `apollo-upload-client` files.
5. Start the app, and test in the browser.

**Comment by yaacovCR** [comment]
Not sure if this is windows thing:

C:\Users\Yaacov\Documents\github\apollo-upload-examples\app>npx install-from ..\..\apollo-upload-client
npx: installed 5 in 2.833s
(node:8816) UnhandledPromiseRejectionWarning: Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:8816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Pull request merged**
