### PR TITLE
Pull out babelrc

### PR DESCRIPTION
**Pull request by zackify**
This will fix the problem with react native.

### CODE REVIEW

**Comment by jaydenseric** [comment]
Thanks for helping out! Couple of things before merging:

1. Remove the new `.npmignore` – we are already specifying `files` in `package.json`.
2. Add a `changelog.md` entry under a `next` version heading. Add "Blah blah, fixing [issuelink] via [pullrequestlink]".

**Comment by zackify** [comment]
Thanks for merging this so fast!!!

**Comment by jaydenseric** [comment]
This is now live in `apollo-upload-client@5.0.0-beta.1` – once verified there are no issues with this release we can move out of of beta.

**Comment by giautm** [comment]
@jaydenseric: I still got problem with babel, i have to install there transformer to make it work. But i'm not sure, because i'm removed 'node_modules' and try re-install all of modules. The internet at my country temporary down for a time. Give me a day to verify problem. Thanks.

**Comment by giautm** [comment]
Yeah, it working without install transformers. 👍

**Pull request merged**
