### PR TITLE
Add link to apollo_upload_server-ruby

### PR DESCRIPTION
**Pull request by fuelen**
Hi all!

I have implemented apollo-upload-server in ruby for Ruby on Rails.

### CODE REVIEW

**Comment by jaydenseric** [comment]
Thats awesome! Does it use v2 of the [GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec)? I have only just [got my head around](https://github.com/jaydenseric/apollo-upload-server/releases/tag/v4.0.0-alpha.2) a stable v2 spec implementation myself.

Before recommending it to users we need to be sure that it matches the API/functionality of `apollo-upload-server`, otherwise we can caveat the differences or note it is alpha. I don't know much about Ruby so I don't know if Node.js concepts such as promises and streams translate across, so I don't know if it makes sense to try to match things like `scalar Upload`.

You might also like to append a link [here](https://github.com/jaydenseric/graphql-multipart-request-spec#relevant-projects).

**Comment by fuelen** [comment]
@jaydenseric Not, it implements the only v1 of the spec. I'll update readme in my implementation with these specifications and recommended version of the client library. I looked at the original apollo-upload-server implementation and made similar stuff.
We have similar thing to `scalar Upload` - `ApolloUploadServer::Upload`.

**Comment by jaydenseric** [comment]
I would strongly advise updating to the latest spec if you can, since it is being integrated into the official `apollo-link-http` package.

**Comment by fuelen** [comment]
Okay, we will make a new version later when developing some new project.

**Comment by fuelen** [comment]
We have released new version 2.0.0.alpha.1. It uses v2 of multipart request spec.

**Comment by jaydenseric** [comment]
Greate news 🙌

**Pull request merged**
