### PR TITLE
changes on Options

### PR DESCRIPTION
**Pull request by tomsvogel**
Hey i did those changes, because i need the options.header also sended to server because of user auth. 

Sorry for the commit with the wrong formatting.

### CODE REVIEW

**Comment by jaydenseric** [comment]
I'm not sure what you mean, in v4.0.2 you should be able to set headers ok?

```js
const networkInterface = createNetworkInterface({
  uri: '/graphql',
  opts: {
    headers: {
      authorization: `Bearer ${accessToken}`
    }
  }
})
```

**Comment by tomsvogel** [comment]
i am using this, http://dev.apollodata.com/react/auth.html#Header to for auth http://dev.apollodata.com/react/auth.html#Header
this is working for normal apollo fallback but not with options.opts

**Comment by benbender** [comment]
Having the same prob. So +1 :)

Thanks for your work!

**Comment by jaydenseric** [comment]
Thanks for your patience guys, please let me know if everything is working ok now in [v4.0.3](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v4.0.3).

I was using this package heavily a few weeks ago in my last project and was the first to notice and fix any issues. The reason a few have been slipping between the cracks recently is because I have not yet built upload functionality into my current project; I have been relying on users to report issues with pull requests and confirm fixes. Soon I will be using it heavily again and patches should be more timely.

**Comment by amannn** [comment]
Works great now. Thanks for the fix @tomsvogel!

**Pull request merged**
