### PR TITLE
Add FileInput implement

### PR DESCRIPTION
**Pull request by giautm**
Fix for https://github.com/jaydenseric/apollo-upload-client/issues/10#issuecomment-310314433

on React Native, upload file via:
```
import { FileInput } from 'apollo-upload-client'

// Example usage
graphql(UPDATE__MUTATION, {
  props: ({ mutate }) => ({
    update: (input) => {
      const clientMutationId = Date.now();

      return mutate({
        variables: {
          input: {
            ...input,
            clientMutationId,
            signature: new FileInput({
                "name": "file_0",
                "type": "image/png",
                "uri": "/Users/admin/Library/Developer/CoreSimulator/Devices/C02A708F-7003-4747-BB09-AA35530AFAC8/data/Containers/Data/Application/44243AD1-906B-4C2E-AC28-6D700BA99609/tmp/ReactABI17_0_0Native/CA1AD1AC-2B6D-47EB-9AE3-528A537E8AC7.png"
            }),
            photos: FileInput.fromArray([{
                "name": "file_1",
                "type": "image/png",
                "uri": "/Users/admin/Library/Developer/CoreSimulator/Devices/C02A708F-7003-4747-BB09-AA35530AFAC8/data/Containers/Data/Application/44243AD1-906B-4C2E-AC28-6D700BA99609/tmp/ReactABI17_0_0Native/CA1AD1AC-2B6D-47EB-9AE3-528A537E8AC7.png"
            }, {
                "name": "file_2",
                "type": "image/png",
                "uri": "/Users/admin/Library/Developer/CoreSimulator/Devices/C02A708F-7003-4747-BB09-AA35530AFAC8/data/Containers/Data/Application/44243AD1-906B-4C2E-AC28-6D700BA99609/tmp/ReactABI17_0_0Native/CA1AD1AC-2B6D-47EB-9AE3-528A537E8AC7.png"
            }]),
          },
        },
      });
    },
  }),
}),
```

### CODE REVIEW

**Comment by jaydenseric** [comment]
I think our current check is a little too strict as I think `name` and `type` [is optional for RN file objects](https://github.com/facebook/react-native/blob/34edf92cbf1dbf7a71c9140921ac4d5e88122622/Libraries/Network/FormData.js#L24). This strategy of using a class would definitely solve the risk of false positives and ease the strictness.

It would make working with RN files a little more complicated, and the bundle size of non RN projects will unfairly increase as the new class has to be imported for the file checks in the `extractRequestFiles` helper.

I'm leaning towards doing it. This PR needs a bit more polish; I'll jump in where I can.

**Comment by jaydenseric** [comment]
@giautm do you need me to publish a risky beta to test this out?

**Comment by jaydenseric** [comment]
This is now live in `apollo-upload-client@5.0.0-beta.1` – once verified there are no issues with this release we can move out of of beta.

**Comment by giautm** [comment]
I checked out, it work fine. :)

**Pull request merged**
